### ISSUE TITLE
Fatal Error On Single Product Temaplte

### ISSUE THREAD

**Issue by chadms** [yeswycan/woocommerce-code#1]
Hi!

Thanks for the plugin! I'm running the code on my store and displays ok at the end, but I am unable to access the editor. I am getting the following error.

Line 173
Message Uncaught Error: Call to a member function get_id() on bool in /home/customer/www/lasjaar.cl/public_html/wp-content/plugins/yotpo-social-reviews-for-woocommerce/wc_yotpo.php:173 Stack trace: #0 /home/customer/www/lasjaar.cl/public_html/wp-content/plugins/yotpo-social-reviews-for-woocommerce/wc_yotpo.php(152): wc_yotpo_get_product_data(false) #1 /home/customer/www/lasjaar.cl/public_html/wp-includes/shortcodes.php(356): wc_yotpo_show_buttomline('', '', 'wycan_yotpo_sta...') #2 [internal function]: do_shortcode_tag(Array) #3 /home/customer/www/lasjaar.cl/public_html/wp-includes/shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(wycan_...', 'do_shortcode_ta...', '[wycan_yotpo_st...') #4 /home/customer/www/lasjaar.cl/public_html/wp-content/plugins/elementor/includes/widgets/shortcode.php(130): do_shortcode('[wycan_yotpo_st...') #5 /home/customer/www/lasjaar.cl/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2208): Elementor\Widget_Shortcode->render() #6 /home/customer/www/lasjaar.cl/pu
File /home/customer/www/lasjaar.cl/public_html/wp-content/plugins/yotpo-social-reviews-for-woocommerce/wc_yotpo.php

Any clues?

Thanks for the contribution! 👍

**Comment by yeswycan** [comment]
Hi,

It’s weird since I don’t have any problem and I’m using it.

Can you provide me screenshot of where u paste the code on ur functions.php please?
It’s for the stars or the comment section ?
I assume, you are using all plugins with the latest version ? Elementor & YotPo ?

Josselyn
